# cloudbuild.yaml
steps:
# Build request-ride-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/request-ride-service:latest', '.']
  dir: 'rider-domain/request-ride-service'

# Build rider-gateway
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rider-gateway:latest', '.']
  dir: 'rider-domain/rider-gateway'

# Build process-payment-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/process-payment-service:latest', '.']
  dir: 'payment-domain/process-payment-service'

# Build payments-gateway
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/payments-gateway:latest', '.']
  dir: 'payment-domain/payment-gateway'

# Build assign-driver-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/assign-driver-service:latest', '.']
  dir: 'driver-domain/assign-driver-service'

# Build driver-gateway
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/driver-gateway:latest', '.']
  dir: 'driver-domain/driver-gateway'

# Push all images built in the steps above to Artifact Registry
# The image names must match the -t tags in the build steps
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/request-ride-service:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/rider-gateway:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/process-payment-service:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/payments-gateway:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/assign-driver-service:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/driver-gateway:latest'
